main/urls.py
from django.urls import path
from main import views

app_name = "main"

urlpatterns = [
    path("", views.IndexView.as_view(), name='index'),
    path("projects", views.ProjectListView.as_view(), name='projects'),
    path("project/<int:pk>", views.ProjectDetailView.as_view(), name='project'),
    path("contactme", views.ContactView.as_view(), name='contactme'),
    path("aboutme", views.AboutMeView.as_view(), name='aboutme'),
    path("send", views.send, name='send'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    # path("home/", include("main.urls")),
    path("", include("main.urls")),
]

main/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=256)
    date = models.PositiveBigIntegerField()
    scope = models.CharField(max_length=50)
    order = models.PositiveIntegerField()
    main_img = models.CharField(max_length=100)
    summary = models.TextField()
    techical_detail = models.TextField(null=True)
    roles = models.TextField(null=True)
    roles_list = models.TextField(null=True)
    challenges = models.TextField(null=True)
    results = models.TextField(null=True)
    show = models.BooleanField()
    link_text = models.CharField(max_length=200, null=True, blank=True)
    link = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name


class Tech(models.Model):
    name = models.CharField(max_length=100)
    project = models.ManyToManyField(Project)

    def __str__(self):
        return self.name
    

class Img(models.Model):
    url = models.CharField(max_length=100)
    alt = models.CharField(max_length=256)
    position = models.CharField(max_length=100, null=True, blank=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.alt

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from django.http import JsonResponse
import requests
from . import models
from .models import Project

# Create your views here.
class IndexView(TemplateView):
   template_name = "index.html"

   def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context["data"] = "Site under construction, come back soon..."
       context["title"] = "Home"
       return context
   

class ProjectListView(ListView):
   model = models.Project
   template_name = "projects_overview.html"
   ordering = ['order']
   context_object_name = 'projects'

   def get_queryset(self):
        return Project.objects.filter(show=True).order_by("order")

   def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context["title"] = "Projects"
       return context
   
class ProjectDetailView(DetailView):
    model = models.Project
    template_name = "project.html"

    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       project = self.get_object()
       context["title"] = project.name
       context["summary"] = project.summary.split("||||")
       context["techical"] = project.techical_detail.split("||||")
       context["roles"] = project.roles.split("||||")
       context["roles_list"] = project.roles_list.split("||||")
       context["challenges"] = project.challenges.split("||||")
       context["results"] = project.results.split("||||")
       context["main_img"] = project.img_set.filter(position='main').first()
       context["techical_img"] = project.img_set.filter(position='techical').all()
       context["roles_img"] = project.img_set.filter(position='roles').all()
       context["challenges_img"] = project.img_set.filter(position='challenges').all()
       context["results_img"] = project.img_set.filter(position='results').all()
       return context
   

class AboutMeView(TemplateView):
   template_name = "aboutme.html"

   def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context["title"] = "About Me"
       return context
   

class ContactView(TemplateView):
   template_name = "contact.html"

   def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context["title"] = "Contact"
       return context
   
   
def send(request):
    name = request.GET["name"]
    email = request.GET["email"]
    subject = request.GET["subject"]
    message = request.GET["message"]
    formatted_message = f"<@622098365806542868>\n" \
                        f"```\n" \
                        f"New message \n" \
                        f"Name: {name} \n" \
                        f"Email: {email} \n" \
                        f"Subject: {subject}\n" \
                        f"Message: \n" \
                        f"{message}\n" \
                        f"```"

    if name == "" or email == "" or subject == "" or message == "":
        return JsonResponse({"data" : "invalid"}, status=200)

    data = {
        "content": formatted_message
    }

    url = "https://discord.com/api/webhooks/1073698819985899592/MC7ZyK72W0X-5mqAJSf8GqNqVF_FVFeMlu-Konkj50GDK7HiM1PiCFr883qg7zA1waxf"
    requests.post(url, json=data)

    return JsonResponse({"data" : "success"}, status=200)

templates/aboutme.html
{% extends "base/base.html" %}
{% load static %}
{% block body_block %}

<div class="lg:min-h-screen">
    <div class="flex flex-row lg:px-32 font-[Oswald] lg:mt-28">
        <div class="lg:basis-auto basis-full relative">
            <img class="" src="{% static 'CVFoto.jpg' %}" alt="">
            <!-- Screen -->
            <div class="absolute bottom-10 right-0 text-left hidden lg:block">
                <p class="lg:text-5xl text-[rgba(0,0,0,0.5)] font-bold">Hi I'm</p>
                <h2
                    class="text-[rgba(0,0,0,0.5)] my-auto font-bold xl:text-[9rem] text-5xl tracking-tighter leading-none">
                    MICHAEL</h2>
            </div>
            <!-- Mobile -->
            <div class="absolute bottom-0 text-center left-1/2 -translate-x-1/2 lg:translate-x-0 lg:hidden">
                <p class="lg:text-5xl text-2xl text-[rgba(0,0,0,0.5)] font-bold">Hi I'm</p>
                <h2
                    class="text-[rgba(0,0,0,0.5)] my-auto font-bold xl:text-[9rem] text-[4.5rem] tracking-tighter leading-none">
                    MICHAEL</h2>
                <h2
                    class="text-[rgba(0,0,0,0.5)] my-auto font-bold xl:text-[9rem] text-[4.5rem] tracking-tighter leading-none lg:hidden">
                    CAMERLYNCK</h2>
            </div>
        </div>
        <div class="lg:basis-2/3 hidden lg:block bg-[#FF8C00] relative">
            <h2
                class="absolute lg:bottom-10 font-bold xl:text-[9rem] tracking-tighter text-[rgba(0,0,0,0.5)] leading-none">
                CAMERLYNCK</h2>
        </div>
    </div>
</div>

<div class="lg:px-32 px-5">
    <div class="lg:flex lg:flex-row lg:mt-0 mt-5">
        <div class="lg:basis-5/12 font-[Oswald] font-bold lg:text-5xl text-3xl tracking-tighter">
            WHO AM I?
        </div>
        <div class="lg:basis-7/12 text-lg text-justify">
            I am a highly motivated and creative individual with a passion for technology and design. I am currently on
            my last semester of studying Applied Computer Science at Thomas More. In my free time, I enjoy listning to
            music, reading and relaxing at a nice and sunny beach. I am known for my ability to thinkoutside the box and
            my perseverance in solving problems.
        </div>
    </div>

    <div class="lg:flex lg:flex-row mt-16">
        <div class="lg:basis-5/12 font-[Oswald] font-bold lg:text-5xl text-3xl tracking-tighter">
            WHAT ARE MY SKILLS AND EXPERIENCE?
        </div>
        <div class="lg:basis-7/12 text-lg text-justify">
            <p>I have a strong background in full-stack web development, specifically using Node.js, PHP, ASP.NET and
                Django.
                Additionally, I have specialized in Artificial Intelligence where I have learned about machine learning
                techniques including supervised and unsupervised learning, deep learning algorithms such as
                Convolutional Neural Networks (CNNs) and Recurrent Neural Networks (RNNs), and the practical
                applications of AI in data science. I have also delved into natural language processing and have a
                strong understanding of how to process, analyze and generate human-like language.</p>
            <p class="mt-3">Throughout my education and professional experience, I have also honed my skills in Agile
                methodology and
                have successfully implemented it in a variety of projects. Whether working independently or as part of a
                team, I consistently deliver high-quality results that meet project requirements and exceed
                expectations.</p>
        </div>
    </div>

    <div class="lg:flex lg:flex-row mt-16">
        <div class="lg:basis-5/12 font-[Oswald] font-bold lg:text-5xl text-3xl tracking-tighter">
            WHAT PROJECTS HAVE I DONE?
        </div>
        <div class="lg:basis-7/12 text-lg text-justify">
            During my studies, I have been fortunate enough to be involved in several exciting and
            challenging projects throughout my academic career. To showcase my abilities and accomplishments, I have
            carefully selected a few of my proudest projects to display in the <a class="underline"
                href="{% url 'main:projects' %}">Projects</a> section of this website. Here,
            you will find detailed information about each project, including technical specifications, obstacles faced,
            and outcomes achieved. Additionally, I have made the code for some of my public projects available for
            review on my <a href="https://github.com/MichaelCamerlynck" class="underline">GitHub</a> page. By visiting
            this section, you will get a comprehensive understanding of my skills,
            creativity, and problem-solving abilities.
        </div>
    </div>

    <div class="lg:flex lg:flex-row mt-16">
        <div class="lg:basis-5/12 font-[Oswald] font-bold lg:text-5xl text-3xl tracking-tighter">
            WHAT CAN I DO FOR YOU?
        </div>
        <div class="lg:basis-7/12 text-lg text-justify">
            I am confident that I can bring my expertise in full-stack development and experience in project management
            to your organization. My skills and experience allow me to quickly understand your needs and deliver
            high-quality solutions that meet your requirements. I am highly adaptable, always willing to expand my
            knowledge and embrace new technologies to best meet the demands of your projects. Furthermore, my strong
            learning capability allows me to quickly grasp new frameworks and techniques, ensuring that I can provide a
            high level of support at all times.
        </div>
    </div>

    <div class="lg:flex lg:flex-row mt-16">
        <div class="lg:basis-5/12 font-[Oswald] font-bold lg:text-5xl text-3xl tracking-tighter">
            HOW TO CONTACT ME
        </div>
        <div class="lg:basis-7/12 text-lg text-justify">
            You can find more information on how to get in touch <a class="underline" href="{% url 'main:contactme' %}">here</a>
        </div>
    </div>

    <div class="lg:flex lg:flex-row mt-24 mb-10">
        <div class="lg:basis-5/12 font-[Oswald] font-bold lg:text-5xl text-3xl tracking-tighter">
            <a href="{% static 'Michael_Camerlynck-CV.pdf' %}" download>CV</a>
        </div>
        <div class="lg:basis-7/12 text-lg text-justify">
            <a href="{% static 'Michael_Camerlynck-CV.pdf' %}" download>
                <img src="{% static 'CV.png' %}" alt="">
            </a>
        </div>
    </div>
</div>

{% endblock %}

templates/base/navbar.html
{% load static %}

    <ul class="border-2 inline-block text-center text-white uppercase font-[Karla] bg-[#1C1C1E]">
        <li class="text-xs text-[#1C1C1E] bg-white px-1 py-5 font-extrabold tracking-tighter">
            <img class="max-h-10 mx-auto mb-5" src="{% static 'logo.svg' %}" alt="">
            <p>Michael</p>
            <p>Camerlynck</p>
        </li>
        <ul class="text-xl font-extrabold tracking-tighter">
            <li style="writing-mode: vertical-rl;" class="rotate-180 mx-auto my-14">
                <a href="{% url 'main:index' %}">Home</a>
            </li>
            <li style="writing-mode: vertical-rl;" class="rotate-180 mx-auto my-14">
                <a href="{% url 'main:aboutme' %}">About</a>
            </li>
            <li style="writing-mode: vertical-rl;" class="rotate-180 mx-auto my-14">
                <a href="{% url 'main:projects' %}">Projects</a>
            </li>
            <li style="writing-mode: vertical-rl;" class="rotate-180 mx-auto my-14">
                <a href="{% url 'main:contactme' %}">Contact</a>
            </li>
        </ul>
    </ul>

templates/base/navmobile.html
{% load static %}
<ul class="flex justify-around align-middle py-2 bg-[#1C1C1E] text-white font-bold">
    <li><img class="max-h-10" src="{% static 'logo-white.svg' %}" alt=""></li>
    <li class="my-auto"><a href="{% url 'main:index' %}">HOME</a></li>
    <li class="my-auto"><a href="{% url 'main:aboutme' %}">ABOUT</a></li>
    <li class="my-auto"><a href="{% url 'main:projects' %}">PROJECTS</a></li>
    <li class="my-auto"><a href="{% url 'main:contactme' %}">CONTACT</a></li>
</ul>

templates/base/oldbase.html
<!DOCTYPE html>
{% load static %}
{% load tailwind_tags %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
    <title>{{ title }}  | Michael Camerlynck</title>
    <link href="https://cdn.jsdelivr.net/gh/hung1001/font-awesome-pro-v6@44659d9/css/all.min.css" rel="stylesheet"
        type="text/css" />
    <link rel="shortcut icon" type="image/png" href="{% static 'logo.ico' %}" />
    <!-- <link rel="stylesheet" href="{% static 'img/styling.css' %}"> -->
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Karla:wght@400;500;700;800&display=swap');

        #signature {
            stroke-dasharray: 350;
            stroke-dashoffset: 350;
            animation: sign 8s ease;
            animation-fill-mode: forwards;
            animation-iteration-count: infinite;
        }

        @keyframes sign {
            40% {
                stroke-dashoffset: 1;
            }

            81% {
                opacity: 1;
            }

            100% {
                opacity: 0;
                stroke-dashoffset: 0;
            }
        }
    </style>
</head>

<body class="sm:px-20 bg-[#1C1C1E]">
    <div class="flex flex-row">
        <div class="hidden lg:block basis-1/12">
            {% include "./navbar.html" %}
        </div>
        <div class="basis-full sm:basis-11/12 static">
            {% block body_block %}
            {% endblock %}
        </div>
    </div>
    {% include "./footer.html" %}
</body>

</html>

templates/contact.html
{% extends "base/base.html" %}
{% load static %}
{% block body_block %}

<div class="px-5 lg:px-0 lg:pr-32 lg:pl-20 lg:mt-28 mb-12">
    <div id="toast"></div>

    <div class="lg:flex lg:flex-row lg:mb-16 mb-10">
        <div class="basis-8/12">
            <h1 class="lg:text-5xl text-4xl lg:mb-0 mb-4 font-bold font-[Oswald]">GET IN TOUCH</h1>
        </div>
        <div class="basis-4/12 text-right lg:mb-0 mb-5">
            <div class="text-2xl text-left">
                <p class="mb-2">
                    <i class="fa-solid fa-envelope"></i>
                    <a href="mailto:michael@camerlynck.com">michael@camerlynck.com</a>
                </p>
                <p>
                    <i class="fa-brands fa-linkedin"></i>
                    <a target="_blank" href="https://www.linkedin.com/in/michael-camerlynck/">MichaelCamerlynck</a>
                </p>
            </div>
        </div>
    </div>

    <div class="lg:flex lg:flex-row">
        <div class="basis-8/12 lg:mb-0 mb-2">
            For a faster response, you can contact me through the form.
        </div>
        <div class="basis-4/12">
            <form action="">
            <div class="flex flex-col">
                <label for="name" class="text-xl tracking-widest mb-1">NAME</label>
                <input type="text" id="name" placeholder="Name" required
                    class="bg-[#1C1C1E] border-2 border-white focus:border-white">
            </div>
            <div class="flex flex-col mt-8">
                <label for="email" class="text-xl tracking-widest mb-1">E - MAIL</label>
                <input type="email" id="email" placeholder="E - Mail" required
                    class="bg-[#1C1C1E] border-2 border-white focus:border-white">
            </div>

            <div class="flex flex-col mt-8">
                <label for="subject" class="text-xl tracking-widest mb-1">SUBJECT</label>
                <input type="text" id="subject" placeholder="Subject" required
                    class="bg-[#1C1C1E] border-2 border-white focus:border-white">
            </div>

            <div class="flex flex-col mt-8">
                <label for="message" class="text-xl tracking-widest mb-1">MESSAGE</label>
                <textarea id="message" placeholder="Message" required
                    class="bg-[#1C1C1E] border-2 border-white focus:border-white" rows="5"></textarea>
            </div>

            <div class="mt-8 bg-white text-[#1C1C1E] text-center py-2 text-xl font-bold">
                <input id="submit" type="submit" value="SEND" class="tracking-widest">
            </div>
            </form>
        </div>
    </div>
</div>

<script>
    $("form").submit(function (e) {
        e.preventDefault()

        const data = {
            name: $("#name").val(),
            email: $("#email").val(),
            subject: $("#subject").val(),
            message: $("#message").val(),
        };

        $.ajax({
            type: "GET",
            url: "{% url 'main:send' %}",
            data: data,
            success: function (response) {
                $('form')[0].reset()
                $("#toast").append(`
                    <div class="flex items-center justify-between max-w-md p-4 absolute top-5 right-10 bg-white border rounded-md shadow-sm toast font-[Inconsolata]">
                        <div class="flex items-center">
                            <svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 text-green-500 mr-4" viewBox="0 0 20 20" fill="currentColor">
                                <path fill-rule="evenodd"
                                    d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                                    clip-rule="evenodd" />
                            </svg>
                            <p class="ml-3 text-sm font-bold text-green-600">Message sent! I will get to you shortly.</p>
                        </div>
                        <span class="inline-flex items-center cursor-pointer">
                            <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 text-gray-600 close" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                            </svg>
                        </span>
                    </div>`
                )
            }
        })
    })

    $("body").on('click', '.toast', function () {
        $(".toast").fadeOut("fast")
    })
</script>

{% endblock %}

templates/index.html
{% extends "base/base.html" %}
{% load static %}
{% block body_block %}
<header class="sm:min-h-screen flex flex-col justify-center snap-y snap-center snap-mandatory">

    <div class="bg-[#FF8C00] sm:ml-32 py-4 sm:py-0">
        <div
            class="sm:text-4xl text-xl ml-3 font-bold tracking-wide sm:pt-0 pt-3 sm:ml-10 sm:mt-7 font-[Oswald] text-[rgba(0,0,0,0.4)] sm:text-left text-center">
            STUDENT &#183; DEVELOPER &#183; DESIGNER
        </div>
        <div
            class="font-[Oswald] text-[rgba(255,255,255,0.5)] sm:text-right text-center pb-10 pt-8 sm:pt-64 sm:pb-28 sm:text-[11rem] text-[4rem] font-bold sm:flex sm:flex-col justify-end sm:tracking-[-0.62rem] sm:leading-[0.85] leading-[0.9]">
            <div>MICHAEL</div>
            <div>CAMERLYNCK</div>
        </div>
        <!-- <div>
            <img class="max-h-[30rem] absolute bottom-0 left-[25rem]" src="{% static 'CVFoto.jpg' %}" alt="">
        </div> -->
    </div>

</header>

<div class="min-h-screen flex flex-col justify-center snap-y snap-center snap-mandatory">
    <figure class="mx-auto mb-10 sm:hidden">
        <img class="max-w-[16rem]" src="{% static 'CVFoto.jpg' %}" alt="">
    </figure>

    <div class="sm:mx-80 relative">
        <!-- Screen -->
        <div class="hidden lg:block absolute sm:right-20 sm:-top-6 bg-[#1C1C1E] sm:px-4 px-2">
            <h2 class="sm:text-5xl text-xl font-bold text-[#FF8C00] font-[Oswald]">ABOUT ME</h2>
        </div>
        <!-- Mobile -->
        <div class="lg:hidden absolute left-8 -top-1 bg-[#1C1C1E] sm:px-4 px-2">
            <h2 class="text-4xl font-bold text-[#FF8C00] font-[Oswald]">ABOUT ME</h2>
        </div>
        <div class="flex flex-row sm:m-0 m-4 border px-4 sm:pl-14 py-10">
            <div class="sm:basis-4/12 hidden lg:block relative">
                <img class="h-[32rem] -top-44 absolute" src="{% static 'PP.jpg' %}" alt="">
            </div>
            <div class="sm:basis-8/12 basis-full">
                <p>Hello and welcome to my online portfolio! My name is Michael, and I am thrilled to have you here to
                    learn more about me and my work in the tech industry. Whether you are here to learn more about my
                    background, skills, or past projects, I aim to provide you with all the information you need to get
                    a comprehensive understanding of who I am and what I can bring to the table.
                    <a href="{% url 'main:aboutme' %}">
                        <p class="mt-5 font-bold font-[Oswald] text-xl text-[#FF8C00]">
                            READ MORE
                            <i class="fa-solid fa-chevron-right"></i>
                        </p>
                    </a>
            </div>

        </div>
    </div>
</div>

<div class="min-h-screen flex flex-col justify-center snap-y snap-center snap-mandatory">
    <figure class="mx-auto mb-10 sm:hidden">
        <img class="max-w-[16rem]" src="{% static 'imgs/Artificial_Img_1.png' %}" alt="">
    </figure>

    <div class="sm:mx-80 relative">
        <!-- Screen -->
        <div class="hidden lg:block absolute sm:left-20 sm:-top-6 bg-[#1C1C1E] sm:px-4 px-2">
            <h2 class="sm:text-5xl text-xl font-bold text-[#FF8C00] font-[Oswald]">PAST PROJECTS</h2>
        </div>
        <!-- Mobile -->
        <div class="lg:hidden absolute left-8 -top-1 bg-[#1C1C1E] sm:px-4 px-2">
            <h2 class="text-4xl font-bold text-[#FF8C00] font-[Oswald]">PAST PROJECTS</h2>
        </div>
        <div class="flex flex-row sm:m-0 m-4 border px-4 sm:pl-14 py-10">
            <div class="sm:basis-8/12 basis-full pr-8">
                <p>I am excited to share with you my portfolio of past projects, showcasing my experience and skills in
                    the tech industry. Each project is a testament to my creativity, problem-solving abilities, and
                    technical expertise. I have hand-selected some of my most impactful and innovative projects to
                    showcase here, and I believe they will provide you with a clear picture of my abilities. So, without
                    further ado, let's take a look at some of the work I have done!</p>
                <a href="{% url 'main:projects' %}">
                    <p class="mt-5 font-bold font-[Oswald] text-xl text-[#FF8C00]">
                        <i class="fa-solid fa-chevron-left"></i>
                        SEE ALL
                    </p>
                </a>
            </div>
            <div class="sm:basis-4/12 hidden lg:block relative">
                <img class="max-h-[32rem] -top-44 absolute" src="{% static 'imgs/Artificial_Img_1.png' %}" alt="">
            </div>

        </div>
    </div>
</div>

{% endblock %}

templates/projects_overview.html
{% extends "base/base.html" %}
{% load static %}
{% block body_block %}

<ul class="font-[Inconsolata] last:border-none lg:text-right">
    {% for project in projects %}
    <li class="flex flex-col py-6 lg:ml-28 mx-4 lg:mr-10 last:border-none border-white border-b-[1px]">
        <p class="lg:text-2xl text-xl mb-4">PROJECT / {{forloop.counter|default:0|stringformat:"02d"}}</p>
        <a href="{% url 'main:project' pk=project.id %}">
            <h2 class="lg:text-[7rem] font-[900] lg:leading-[0.8] text-5xl font-[Oswald] tracking-tight">{{project.name}}</h2>
        </a>
        <ul class="lg:flex lg:justify-end lg:mt-8 mt-3 lg:text-[1.3rem] text-[1.05rem]">
            <ul class="lg:flex">
                <li class="lg:mr-3">{{project.date}}<span class="hidden lg:inline-block lg:ml-3">|</span></li>
                <li class="lg:mr-3">{{project.scope}}<span class="hidden lg:inline-block lg:ml-3">|</span></li>
            </ul>
            <ul class="flex flex-wrap">
                {% for tech in project.tech_set.all %}
                <li class="mr-3">
                    {% if forloop.counter != 1 %}
                    <span class="mr-1">/</span>
                    {% endif %}
                    {{tech.name}}
                </li>
                {% endfor %}
            </ul>
        </ul>
        <div class="flex lg:justify-end lg:my-8 mt-3 overflow-x-auto hidden-scrollbar">
            {% for img in project.img_set.all %}
            <a href="{% url 'main:project' pk=project.id %}" class="shrink-0 mr-3 lg:mr-0 lg:ml-5 last:mr-0">
                <img class="lg:max-h-56 max-h-36" src="{% static img.url %}"
                alt="{{img.alt}}">
            </a>
            
            {% endfor %}
        </div>
    </li>
    {% endfor %}
</ul>

{% endblock %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>